apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-kafka-prod-like.yaml
    target:
      kind: Kafka
      name: realtime-lab-kafka
  - path: patch-kafka-nodepool-prod-like.yaml
    target:
      kind: KafkaNodePool
      name: dual-role
  - path: patch-flink-prod-like.yaml
    target:
      kind: FlinkDeployment
      name: realtime-lab-flink
  - path: patch-topics-prod-like.yaml
