apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-lab-api
  namespace: realtime-lab
spec:
  replicas: 2
  minReadySeconds: 10
  progressDeadlineSeconds: 300
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    spec:
      containers:
        - name: api
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: realtime-lab-api-secrets
                  key: api-token
                  optional: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: realtime-lab-api
