apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-lab-api
  namespace: realtime-lab
spec:
  replicas: 2
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: realtime-lab-api
