apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: realtime-lab-flink
  namespace: realtime-lab
spec:
  flinkConfiguration:
    state.backend.type: rocksdb
    state.backend.incremental: "true"
    taskmanager.numberOfTaskSlots: "4"
    execution.checkpointing.interval: "10000"
    execution.checkpointing.dir: s3://replace-me-realtime-lab/flink/checkpoints
    execution.checkpointing.savepoint-dir: s3://replace-me-realtime-lab/flink/savepoints
    high-availability.type: kubernetes
    high-availability.storageDir: s3://replace-me-realtime-lab/flink/ha
  jobManager:
    replicas: 2
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    replicas: 2
    resource:
      memory: "4096m"
      cpu: 2
  job:
    parallelism: 4
    upgradeMode: savepoint
