apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: realtime-lab-flink
  namespace: realtime-lab
spec:
  flinkConfiguration:
    execution.checkpointing.mode: EXACTLY_ONCE
  job:
    args:
      - --bootstrapServers
      - realtime-lab-kafka-kafka-bootstrap:9092
      - --rawTopic
      - transactions.raw
      - --replayTopic
      - transactions.replay
      - --merchantRiskProfileTopic
      - merchant_risk_profiles
      - --alertTopic
      - alerts.fraud
      - --aggregateTopic
      - transactions.aggregates
      - --dlqTopic
      - transactions.dlq
      - --consumerGroup
      - flink-realtime-lab
      - --sinkDeliveryGuarantee
      - EXACTLY_ONCE
      - --checkpointIntervalMillis
      - "10000"
      - --watermarkDelaySeconds
      - "10"
      - --allowedLatenessSeconds
      - "30"
