apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: realtime-lab-flink
  namespace: realtime-lab
spec:
  flinkConfiguration:
    execution.checkpointing.mode: EXACTLY_ONCE
  job:
    args:
      - --bootstrapServers
      - realtime-lab-kafka-kafka-bootstrap:9092
      - --rawTopic
      - transactions.raw
      - --replayTopic
      - transactions.replay
      - --merchantRiskProfileTopic
      - merchant_risk_profiles
      - --alertTopic
      - alerts.fraud
      - --aggregateTopic
      - transactions.aggregates
      - --dlqTopic
      - transactions.dlq
      - --consumerGroup
      - flink-realtime-lab
      - --sourceIsolationLevel
      - read_committed
      - --sinkDeliveryGuarantee
      - EXACTLY_ONCE
      - --checkpointIntervalMillis
      - "10000"
      - --watermarkDelaySeconds
      - "10"
      - --allowedLatenessSeconds
      - "30"
      - --sourceIdleTimeoutSeconds
      - "30"
      - --maxFutureSkewSeconds
      - "300"
      - --deduplicationTtlHours
      - "24"
      - --sourceStartupMode
      - LATEST
      - --transactionalIdPrefix
      - realtime-lab-k8s-exactly-once
      - --riskHighFraudScore
      - "0.92"
      - --riskHighAmount
      - "1000.0"
      - --riskHighIpRisk
      - "80"
      - --riskBurstCountThreshold
      - "5"
      - --riskBurstAmountThreshold
      - "3000.0"
      - --riskMerchantCountThreshold
      - "25"
      - --riskMerchantAmountThreshold
      - "15000.0"
      - --riskMerchantAvgFraudScoreThreshold
      - "0.72"
