apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: realtime-lab-flink
  namespace: realtime-lab
spec:
  image: realtime-lab-flink-job:2.1.2
  flinkVersion: v2_1
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "4"
    state.backend.type: hashmap
    execution.checkpointing.interval: "10000"
    execution.checkpointing.mode: AT_LEAST_ONCE
    execution.checkpointing.externalized-checkpoint-retention: RETAIN_ON_CANCELLATION
    restart-strategy.type: fixed-delay
    restart-strategy.fixed-delay.attempts: "3"
    restart-strategy.fixed-delay.delay: 10 s
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  taskManager:
    replicas: 1
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/realtime-lab-flink-job.jar
    entryClass: io.github.jaejungscene.realtimelab.job.RealTimeAlertJob
    parallelism: 2
    upgradeMode: stateless
    args:
      - --bootstrapServers
      - realtime-lab-kafka-kafka-bootstrap:9092
      - --rawTopic
      - transactions.raw
      - --replayTopic
      - transactions.replay
      - --merchantRiskProfileTopic
      - merchant_risk_profiles
      - --alertTopic
      - alerts.fraud
      - --aggregateTopic
      - transactions.aggregates
      - --dlqTopic
      - transactions.dlq
      - --consumerGroup
      - flink-realtime-lab
      - --sinkDeliveryGuarantee
      - AT_LEAST_ONCE
      - --checkpointIntervalMillis
      - "10000"
      - --watermarkDelaySeconds
      - "10"
      - --allowedLatenessSeconds
      - "30"
      - --sourceIdleTimeoutSeconds
      - "30"
      - --maxFutureSkewSeconds
      - "300"
      - --sourceStartupMode
      - LATEST
      - --transactionalIdPrefix
      - realtime-lab-k8s
