apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: realtime-lab-flink
  namespace: realtime-lab
spec:
  image: realtime-lab-flink-job:2.1.2
  flinkVersion: v2_1
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "4"
    state.backend.type: hashmap
    execution.checkpointing.interval: "10000"
    execution.checkpointing.mode: AT_LEAST_ONCE
    restart-strategy.type: fixed-delay
    restart-strategy.fixed-delay.attempts: "3"
    restart-strategy.fixed-delay.delay: 10 s
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  taskManager:
    replicas: 1
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/realtime-lab-flink-job.jar
    entryClass: com.example.realtimelab.job.RealTimeAlertJob
    parallelism: 2
    upgradeMode: stateless
    args:
      - --bootstrapServers
      - realtime-lab-kafka-kafka-bootstrap:9092
      - --rawTopic
      - transactions.raw
      - --replayTopic
      - transactions.replay
      - --alertTopic
      - alerts.fraud
      - --aggregateTopic
      - transactions.aggregates
      - --dlqTopic
      - transactions.dlq
