apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transactions-raw
  namespace: realtime-lab
  labels:
    strimzi.io/cluster: realtime-lab-kafka
spec:
  topicName: transactions.raw
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transactions-replay
  namespace: realtime-lab
  labels:
    strimzi.io/cluster: realtime-lab-kafka
spec:
  topicName: transactions.replay
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transactions-aggregates
  namespace: realtime-lab
  labels:
    strimzi.io/cluster: realtime-lab-kafka
spec:
  topicName: transactions.aggregates
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: alerts-fraud
  namespace: realtime-lab
  labels:
    strimzi.io/cluster: realtime-lab-kafka
spec:
  topicName: alerts.fraud
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: transactions-dlq
  namespace: realtime-lab
  labels:
    strimzi.io/cluster: realtime-lab-kafka
spec:
  topicName: transactions.dlq
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
